# Cloud Build configuration for demo-agent
# This file configures automated builds for Google Cloud Run deployment

steps:
  # Build Docker image using Cloud Run Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'deploy/Dockerfile.cloudrun'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/demo-repo/demo-agent:${SHORT_SHA}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/demo-repo/demo-agent:latest'
      - '.'

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/demo-repo/demo-agent'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'demo-agent'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/demo-repo/demo-agent:${SHORT_SHA}'
      - '--region=us-central1'
      - '--platform=managed'
      - '--service-account=demo-service-sa@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'
      - '--concurrency=80'
      - '--add-cloudsql-instances=${PROJECT_ID}:us-central1:demo-db'
      - '--set-env-vars=^;^GCP_PROJECT_ID=${PROJECT_ID};GCP_LOCATION=us-central1;MODEL=gemini-2.5-flash;ENABLE_CLERK_AUTH=true;CLERK_FRONTEND_API=sweet-cod-61.clerk.accounts.dev;CORS_ALLOW_ORIGINS=*;CORS_ALLOW_CREDENTIALS=false;CORS_ALLOW_HEADERS=Authorization,Content-Type,X-Request-ID,X-Clerk-Token;LOG_JSON_FORMAT=true;LOG_LEVEL=INFO;DEMO_MAX_TOKENS=5000;SCHEMA_NAME=test;DB_POOL_MIN_SIZE=2;DB_POOL_MAX_SIZE=10;ENABLE_FINGERPRINT=true'
      - '--set-secrets=DATABASE_URL=database-url:latest,CLERK_PUBLISHABLE_KEY=clerk-publishable-key:latest'

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/demo-repo/demo-agent:${SHORT_SHA}'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/demo-repo/demo-agent:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
